### ISSUE TITLE
hi,图片太多，加载太慢了，而且图标太小了，不易观看，如果改成鼠标hover就显示功能就更好了

### ISSUE THREAD

**Issue by DualWield** [laixintao/ISAAC-Atlas-online#1]

**Comment by laixintao** [comment]
Thanks,过一段时间我会回来重构这个页面，改一下hover和图标。

加载速度好像没有什么解决办法，一次加载完以后一直查，放在github上速度总是不理想。

**Comment by DualWield** [comment]
图片都弄到一张图上吧，用css spirit ，不然加载几十张图就是几十个请求了

**Comment by jostyee** [comment]
@laixintao 还有计划么，现在加载太慢了。。

**Comment by laixintao** [comment]
谢谢回复，最近太忙了，没有时间优化。

可以保存这个网页到本地，因为用的静态的网页防盗github上，所以一次要把所有的内容加载下来，速度暂时想不到什么好的解决办法。如果使用别的cdn，可能也会比github快很多
